runtime: nodejs12
env: standard

includes:
  - server/config/env_variables.yaml

handlers:
  - url: /api/.*
    script: auto

  - url: /static
    static_dir: client/build/static

  - url: /(.*\.(json|ico|js))$
    static_files: client/build/\1
    upload: client/build/.*\.(json|ico|js)$

  - url: .*
    static_files: client/build/index.html
    upload: client/build/index.html
